name: semika - Terraform CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read

env:
  TF_VERSION: "1.12.2"
  TFLINT_VERSION: "v0.47.0"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      ec2: ${{ steps.filter.outputs.ec2 }}
      s3: ${{ steps.filter.outputs.s3 }}
    steps:
      - uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ec2:
              - 'ec2-project/**'
            s3:
              - 's3-project/**'

  terraform-ec2:
    name: Terraform EC2
    needs: detect-changes
    if: needs.detect-changes.outputs.ec2 == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}
      - name: Terraform Init
        run: terraform init
        working-directory: ec2-project
      - name: Terraform Lint
        run: tflint --format compact
        working-directory: ec2-project
      - name: Terraform Format Check
        run: terraform fmt -check -diff
        working-directory: ec2-project
      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: ec2-project
      - name: Terraform Plan
        run: terraform plan -out=tfplan -no-color
        working-directory: ec2-project
      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: ec2-tfplan
          path: ec2-project/tfplan

  terraform-s3:
    name: Terraform S3
    needs: detect-changes
    if: needs.detect-changes.outputs.s3 == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ env.TFLINT_VERSION }}
      - name: Terraform Init
        run: terraform init
        working-directory: s3-project
      - name: Terraform Lint
        run: tflint --format compact
        working-directory: s3-project
      - name: Terraform Format Check
        run: terraform fmt -check -diff
        working-directory: s3-project
      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: s3-project
      - name: Terraform Plan
        run: terraform plan -out=tfplan -no-color
        working-directory: s3-project
      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: s3-tfplan
          path: s3-project/tfplan
